[source.crates-io]
registry = "git://github.com/rust-lang/crates.io-index.git"

[package]
name = "kilo-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.25.0"
lazy_static = "1.4.0"
